## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - nightly
notifications:
  email:
    on_success: never
    on_failure: never

before_script:
  - julia -e 'using Pkg; Pkg.clone("https://github.com/JuliaDynamics/TimeseriesPrediction.jl")'
  - julia -e 'using Pkg; Pkg.add("StaticArrays")'
  - julia -e 'using Pkg; Pkg.add("OrdinaryDiffEq")'

after_success:
  - test $TRAVIS_OS_NAME = "linux" && julia -e 'using Pkg; ENV["PYTHON"]=""; py="PyCall"; Pkg.add(py); Pkg.build(); Pkg.add("PyPlot")'
  - test $TRAVIS_OS_NAME = "linux" && julia -e 'using Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
