site_name:           DynamicalSystems.jl
repo_url:            https://github.com/JuliaDynamics/DynamicalSystems.jl
site_description:    A Julia package for the exploration of chaos in continuous and discrete dynamical systems.
site_author:         George Datseris

theme:               'material'

extra:
  palette:
    primary: 'teal'
    accent: 'deep orange'
  social:
    - type: 'github'
      link: 'https://github.com/JuliaDynamics/DynamicalBilliards.jl'

markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - codehilite
  - extra
  - tables
  - fenced_code

extra_css:
  - assets/Documenter.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

docs_dir: 'build'

pages:
- Introduction: index.md
- System Definition: system_definition.md
- Lyapunov Exponents: lyapunovs.md
- Entropies and Dimensions: entropies.md
- Nonlinear Timeseries Analysis: nlts.md
- Periodicity: periodicity.md
- Contributor Guide: contributors_guide.md
